### ISSUE TITLE
Master different with last release

### ISSUE THREAD

**Issue by zkrhm** [fanout/go-pubcontrol#4]
Hi, I am using glide to resolve dependency. I see that the latest release is 1.0.2. and it still uses old version of go-jwt, however main branch already updated. 

so on glide I set the version to master like 
```yaml

- package: github.com/fanout/go-pubcontrol
  version: master

```
 and **it's works**. but glide will check for latest release by default. so I will leave this note here.
and I hope maintainer can create new release, so this library's user won't have breaking dependency.

**Comment by jkarneges** [comment]
Tagged 1.1.0.

Also removed the Godeps directory as that seems to be not a thing anyone uses anymore.
